#server.port=8081
spring.application.name=railway
spring.datasource.url=jdbc:mysql://root:SCDYLhvHeJXENnKLmlRGfRHLnFQJNhkU@yamabiko.proxy.rlwy.net:34679/railway
spring.datasource.username=root
spring.datasource.password=SCDYLhvHeJXENnKLmlRGfRHLnFQJNhkU
# application.properties
spring.web.resources.static-locations=classpath:/static/

cloudianry.cloud_name=ddmsl3meg
cloudianry.api_key=453371273219892
cloudianry.api_secret=PPLi-PXBfDznaXs1fqHNw-bAcVs

spring.main.allow-bean-definition-overriding=true

spring.jpa.hibernate.ddl-auto = update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

access_key = baf4b88b2fd6c1e95913371ac537f613
BASE_URL = http://api.aviationstack.com/v1/flights
